### ISSUE TITLE
Limiter au maximum légal

### ISSUE THREAD

**Issue by jeeyppmp** [PartiPirate/ppmoney#12]
j'ai remarqué que je pouvais entrer un don de 250 894 €, ce qui fait, réduction d'impôt comprise, une adhésion à 85 313 € seulement. Il vaudrait mieux plafonner au maximum légal.
Ainsi, la somme "Adhésion" + "Don section locale" + "Don" ne doit pas dépasser 7 500 €.

**Comment by Relf-Oc** [comment]
Le maximum de 7500 € c'est le maximum que tu peux donner ou le maximum que tu peux ecrire sur ta declaration?
Je crois que tu peux donner tout ce que tu veux, mais que les impôts ne prennent pas en compte plus de 7500€

**Comment by mistraloz** [comment]
Non non, c'est bien le maximum que tu peux donner (toute formation politique confondue) chaque année. 
Regardes l'article 11-4 sur légifrance : https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000321646

La defiscalisation fait l'objet d'un autre texte dans le code général des impots (de mémoire, mais ce n'est pas le sujet ici). 

Par contre, même s'il n'y a pas d'alerte préalable, j'avais fais un commit pour justement limiter à 7500€ un montant recu (ce qui limite les enmerdes que nous pourrions avoir mais ne les empêchent pas dans l'absolu). 

=> Je suis néanmoins d'avis de mettre ce ticket de coté. Ce n'est pas si souvent qu'on veut nous donner 7000 boules ;).

**Comment by Numero6ppfr** [comment]
"...mettre ce ticket de coté." Ce qui revient à l'enterrer en catimini, et puis c'est le problème de l'AFPP en général et de son trésorier en particulier, qu'il(s) se débrouille(nt) si le montant total adhésion+dons dans la période d'une année civile dépasse  le plafond autorisé par l'art. 11-4 de la loi n° 88-227 du 11 mars 1988 relative à la transparence financière de la vie politique. 
Les garde-fous sont une perte de temps et d'énergie, voyons !
